# Generated by Django 5.2.10 on 2026-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
